# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: SH-NONPROD
variables:
  ACR_NAME: acrfizzbuzz9191
  IMAGE_NAME: FizzBuzzApi
  IMAGE_TAG: $(Build.BuildId)
  
steps:
  - task: AzureClI@2
    displayName: 'Login to Azure'
    inputs:
      azureSubscription: 'NONPROD'  
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az acr login --name $(ACR_NAME)
  
  - task: Bash@3
    displayName: 'Build and Tag Docker Image'
    inputs:
      targetType: inline
      script: |
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) .
        docker tag $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
  
  - task: Bash@3
    displayName: 'Push Docker Image to ACR'
    inputs:
      targetType: inline
      script: |
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest